root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "bin", ".git", ".cache", "vendor", "node_modules", "resources", "public"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[misc]
  clean_on_exit = true
